### ISSUE TITLE
sendmail path & error reporting

### ISSUE THREAD

**Issue by dready92** [srod/node-mailer#1]
Hello,

your library seems pretty cool, however :

it uses sendmail, and on RedHat sendmail is /usr/lib/sendmail, so not in user path... And the error you return in the callback is the string "error", and not the error object, so it was hard to debug.

**Comment by srod** [comment]
Hello,

This module is on top of "nodemailer", so it's this one how send callback content.

**Comment by dready92** [comment]
Yes but not exactly... in line 35 of your lib/node-mailer.js, you do a 

```
self.callback('error');
```

but it will be more interesting if you did a 

```
self.callback(error);
```

Regards,

Mickael

**Comment by srod** [comment]
You're right, my bad.
It's corrected in 0.1.1.
Thanks !
